[build-system]
requires = [
    "platformdirs>=3.10.0",
    "rich>=13.5.2",
    "setuptools>=65.5.0",
    "googletrans>=3.1.0a0",
    "matplotlib>=3.7.2",
    "wheel"
]

build-backend = "setuptools.build_meta"